.\" -*- nroff -*-
.ds g \" empty
.ds G \" empty
.de Tp
.ie \\n(.$=0:((0\\$1)*2u>(\\n(.1u-\\n(.iu)) .TP
.el .TP "\\$1"
..
.TH PCA-MAPS 1 "13 Jul 2015" "pca-utils version 20150713"
.SH NAME
pca-maps \- generate probability density maps from 2D scores data
.SH SYNOPSIS
.B pca-maps
[
.B \-h
]
.LP
.B pca-maps
\-i \fIINFILE\fR [\fIOPTIONS\fR]
.SH DESCRIPTION
.PP
Prints probability density functions from 2D PCA/PLS scores. I'm going to
level with you; this program is probably useless.
.TP
\fB\-h\fR, \fB-\-help\fR
display a short help message.
.TP
\fB\-i\fR, \fB\-\-input\fR \fIINFILE\fR
scores list input file, formatted according to the list file exported from
Umetrics SIMCA-P+ software. See pca-rand(1) for more information.
.TP
\fB\-D\fR, \fB\-\-divisions\fR \fINDIV\fR
number of grid divisions to create while approximating probability densities.
.SH AUTHOR
Bradley Worley <geekysuavo@gmail.com>
.SH COPYRIGHT
Copyright \(co 2015 Bradley Worley.
.br
This is free software. You may redistribute copies of it under the terms of
the GNU General Public License <http://www.gnu.org/licenses/gpl.html>.
There is NO WARRANTY, to the extent permitted by law.
.SH "SEE ALSO"
.BR pca-bootstrap(1),
.BR pca-dendrogram(1),
.BR pca-distances(1),
.BR pca-ellipses(1),
.BR pca-ellipsoids(1),
.BR pca-overlap(1),
.BR pca-stats(1),
.BR pca-rand(1)
