.\" -*- nroff -*-
.ds g \" empty
.ds G \" empty
.de Tp
.ie \\n(.$=0:((0\\$1)*2u>(\\n(.1u-\\n(.iu)) .TP
.el .TP "\\$1"
..
.TH PCA-OVERLAP 1 "13 Jul 2015" "pca-utils version 20150713"
.SH NAME
pca-overlap \- build p-value overlap tables from scores
.SH SYNOPSIS
.B pca-overlap
[
.B \-h
]
.LP
.B pca-overlap
\-i \fIINFILE\fR [\fIOPTIONS\fR]
.SH DESCRIPTION
.PP
Build an overlap table from PCA/PLS scores in \fBINFILE\fR. The table is
similar in form to the distance matrices produced by pca-distances(1), but
is created in a very specific way. In the output, each pair of groups is
given a p-value that relates to the amount of overlap (used for accepting
the null hypothesis) of the groups. This p-value is calculated in an
identical manner to p-values reported by pca-dendrogram(1).
.TP
\fB\-h\fR, \fB-\-help\fR
display a short help message.
.TP
\fB\-i\fR, \fB\-\-input\fR \fIINFILE\fR
scores list input file, formatted according to the list file exported from
Umetrics SIMCA-P+ software. See pca-rand(1) for more information.
.SH AUTHOR
Bradley Worley <geekysuavo@gmail.com>
.SH COPYRIGHT
Copyright \(co 2015 Bradley Worley.
.br
This is free software. You may redistribute copies of it under the terms of
the GNU General Public License <http://www.gnu.org/licenses/gpl.html>.
There is NO WARRANTY, to the extent permitted by law.
.SH "SEE ALSO"
.BR pca-bootstrap(1),
.BR pca-dendrogram(1),
.BR pca-distances(1),
.BR pca-ellipses(1),
.BR pca-ellipsoids(1),
.BR pca-stats(1),
.BR pca-rand(1),
.BR pca-maps(1)
